scan: use absdiff instead of abs in order to fix GCC7 error
This commit should fix the following GCC7 error:
../../git/lib/dvb/scan.cpp:312:54: error: call of overloaded 'abs(unsigned int)' is ambiguous